### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by wazerstar** [s-ol/csgo-vscripts#7]
Took latest code from master and got it excuted ingame saying saving nade and throwing and throwing again, does not seem to be working.

**Comment by JFingerle** [comment]
Can confirm :(

**Comment by s-ol** [comment]
Well, I haven't tried it since 2015, so I can't really say much about this. Are there any error messages in the console?

**Comment by SergeyKasmy** [comment]
Is the script really of any use anymore when there's now `sv_rethrow_last_grenade`?

**Comment by JFingerle** [comment]
Thanks for your replies!

There are no errors in the console.

I didn't know about the command `sv_rethrow_last_grenade` - this really makes this vscript obsolete.

-> Issue can be closed IMHO
-> Delete repo?

**Comment by s-ol** [comment]
I'm going to archive the repo.
